### ISSUE TITLE
Feature: Implement method aliases to better support IDE autocompletion

### ISSUE THREAD

**Issue by rvanbaalen** [validformbuilder/validformbuilder#60]
### Todo

  - [x] Create HasFieldAliases trait 
- [x] Implement the trait
 - [ ] Make sure elements created with the aliased methods get added to the correct collections
 - [ ] Validate the use of alias methods in ValidWizard

----

I would suggest to implement method aliases to improve IDE autocompletion support.

Some examples:

```php
// Example 1:

$multiField->addField(
    "name",
    ValidForm::VFORM_STRING,
    [
        "required" => true
    ],
    [
        "required" => 'Required field'
    ]
);
```

```php
// Example 2

$radioList = $objArea->addField(
    "radio-list",
    'Label for radio',
    ValidForm::VFORM_RADIO_LIST,
    [
        "required" => true
    ],
    [
        "required" => 'This field is required.'
    ]
);
$radioList->addField('option1', 'Option 1');
$radioList->addField('option2', 'Option 2');

```

Would become

```php
// New situation 1

$multiField->addStringField(
    "name",
    [
        "required" => true
    ],
    [
        "required" => 'Required field'
    ]
);
```

```php
// New situation 2

$radioList = $area->addRadioList(
    "radio-list",
    'Label for radio',
    [
        "required" => true
    ],
    [
        "required" => 'This field is required.'
    ]
);
$radioList->addListOption('option1', 'Option 1');
$radioList->addListOption('option2', 'Option 2');
```

This makes the VFB API more readable and enables type hinting for IDEs. Initially, these methods serve as aliases for the existing `addField` methods where we could later on implement these new methods as the recommended way to use VFB and deprecate the use of `addField`.

What are your two cents on this subject @flangfeldt

**Comment by flangfeldt** [comment]
If you can't possibly stop yourself. ;-)

**Comment by rvanbaalen** [comment]
Referenced wrong issue from commit
